### ISSUE TITLE
recommend pylatex

### ISSUE THREAD

**Issue by Freakwill** [vungocbinh2009/pytexexam#1]
It is better to use `pylatex` to generate the latex code. I am interested in the project, and made a similar one.

**Comment by vungocbinh2009** [comment]
Thank you for the recommendation, that library is great
But I'm quite busy right now, so I can't update immediately. As soon as I have free time, I will do it.

**Comment by vungocbinh2009** [comment]
Thank you for the recommendation, that library is great
But I'm quite busy right now, so I can't update immediately. As soon as I have free time, I will do it.
