### ISSUE TITLE
module "answer" not found

### ISSUE THREAD

**Issue by rclUPC** [vungocbinh2009/pytexexam#3]
Hi,
I was testing the app and I have found this error:

> 
> /usr/local/lib/python3.6/dist-packages/pytexexam/question.py in <module>()
> ----> 1 from answer import Answer
>       2 import random
>       3 from typing import Dict
>       4 
>       5 
> 
> ModuleNotFoundError: No module named 'answer'

`
Something missing?
Regards
Robert

**Comment by vungocbinh2009** [comment]
Hi Robert
Maybe I don't import answer.py file in __init__.py (I haven't use Python for a long time, so I'm not sure)
And you also do not need to import this file to use. You can read README.md to see example.
